dearmoment-team/dear-moment-backend

Dockerfile, README.md, build.gradle.kts, docker-compose.yml, entrypoint.sh, settings.gradle.kts
=> #9 Docker환경에서 디버깅 가능하도록 설정

src/main/kotlin/kr/kro/dearmoment/image/adapter/output/objectstorage/OracleObjectStorageAdapter.kt, src/main/kotlin/kr/kro/dearmoment/image/application/port/output/GetImageFromObjectStoragePort.kt, src/main/kotlin/kr/kro/dearmoment/image/application/service/ImageService.kt, src/main/kotlin/kr/kro/dearmoment/image/domain/Image.kt, src/test/kotlin/kr/kro/dearmoment/image/adapter/output/objectstorage/OracleObjectStorageAdapterTest.kt, src/test/kotlin/kr/kro/dearmoment/image/application/service/ImageServiceTest.kt
=> feat: 객체 스토리지로 부터 특정 개체 public url 생성, 삭제 기능 구현

src/main/kotlin/kr/kro/dearmoment/image/adapter/output/objectstorage/OracleObjectStorageAdapter.kt
=> 이미지 변경사항 적용

src/main/kotlin/kr/kro/dearmoment/like/adapter/input/web/LikeRestAdapter.kt, src/main/kotlin/kr/kro/dearmoment/like/adapter/input/web/dto/GetLikeResponse.kt, src/main/kotlin/kr/kro/dearmoment/like/adapter/output/persistence/JpaLikeRepository.kt, src/main/kotlin/kr/kro/dearmoment/like/adapter/output/persistence/LikePersistenceAdapter.kt, src/main/kotlin/kr/kro/dearmoment/like/application/command/SaveLikeCommand.kt, src/main/kotlin/kr/kro/dearmoment/like/application/port/input/LikeUseCase.kt, src/main/kotlin/kr/kro/dearmoment/like/application/port/output/GetLikePort.kt, src/main/kotlin/kr/kro/dearmoment/like/application/query/ExistLikeQuery.kt, src/main/kotlin/kr/kro/dearmoment/like/application/query/GetLikesQuery.kt, src/main/kotlin/kr/kro/dearmoment/like/application/service/LikeService.kt, src/test/kotlin/kr/kro/dearmoment/like/adapter/input/web/LikeRestAdapterTest.kt, src/test/kotlin/kr/kro/dearmoment/like/adapter/output/persistence/LikePersistenceAdapterTest.kt, src/test/kotlin/kr/kro/dearmoment/like/application/service/LikeServiceTest.kt
이슈 번호: #24
- 유저의 좋아요를 조회할 수 있다.(상품, 작가 별로)
- 좋아요 대상이 존재하는지 여부를 알 수 있다.
=> feat: 유저별 좋아요 조회 및 좋아요 존재 여부 기능 추가 #24

.github/workflows/docker-publish.yml
=> ghcr ci 설정 추가

.github/workflows/docker-publish.yml
=> ci: ghcr 오브젝트 스토리지 secrets 추가

.github/workflows/docker-publish.yml
이슈 번호: N/A
Actions에 사용된 버전들을 최신화 및 github sha 를 사용한 이미지 태그를 추가했습니다.
=> chore : use the latest version of actions

src/main/kotlin/kr/kro/dearmoment/image/adapter/output/objectstorage/OracleObjectStorageAdapter.kt, src/main/kotlin/kr/kro/dearmoment/image/adapter/output/objectstorage/OracleObjectStorageProperties.kt, src/main/kotlin/kr/kro/dearmoment/image/adapter/output/objectstorage/OracleObjectStorageUtil.kt, src/main/kotlin/kr/kro/dearmoment/image/adapter/output/persistence/ImageEntity.kt, src/main/kotlin/kr/kro/dearmoment/image/adapter/output/persistence/ImagePersistenceAdapter.kt, src/main/kotlin/kr/kro/dearmoment/image/adapter/output/persistence/JpaImageRepository.kt, src/main/kotlin/kr/kro/dearmoment/image/application/port/input/UpdateImagePort.kt, src/main/kotlin/kr/kro/dearmoment/image/application/port/output/GetImageFromObjectStoragePort.kt, src/main/kotlin/kr/kro/dearmoment/image/application/port/output/GetImagePort.kt, src/main/kotlin/kr/kro/dearmoment/image/application/service/ImageService.kt, src/main/resources/application.properties, src/test/kotlin/kr/kro/dearmoment/image/adapter/output/objectstorage/OracleObjectStorageAdapterTest.kt, src/test/kotlin/kr/kro/dearmoment/image/adapter/output/persistence/ImagePersistenceAdapterTest.kt, src/test/kotlin/kr/kro/dearmoment/image/application/service/ImageServiceTest.kt
이슈 번호: N/A
- 이미지 url 갱신 시 DB에 해당 이미지 url 업데이트 로직 추가
- oci config 경로 env로 추출
=> 이미지 도메인 리뷰 반영

entrypoint.sh
ATP DB 엔드포인트(tnsnames.ora에 정의된 별칭)를 사용하도록
이슈 번호: N/A
=> chore: db 연결 설정 호스트명 변경 #45

.github/workflows/deploy-to-production.yml, build.gradle.kts, entrypoint.sh, src/main/resources/application.properties
=> chore: OCI deployment configuration YAML 파일 추가

src/main/kotlin/kr/kro/dearmoment/inquiry/adapter/input/web/artist/ArtistInquiryRestAdapter.kt, src/main/kotlin/kr/kro/dearmoment/inquiry/adapter/input/web/artist/dto/CreateArtistInquiryRequest.kt, src/main/kotlin/kr/kro/dearmoment/inquiry/adapter/input/web/artist/dto/GetArtistInquiryResponse.kt, src/main/kotlin/kr/kro/dearmoment/inquiry/adapter/output/persistence/InquiryPersistenceAdapter.kt, src/main/kotlin/kr/kro/dearmoment/inquiry/adapter/output/persistence/artist/ArtistInquiryEntity.kt, src/main/kotlin/kr/kro/dearmoment/inquiry/adapter/output/persistence/artist/ArtistInquiryJpaRepository.kt, src/main/kotlin/kr/kro/dearmoment/inquiry/application/command/CreateArtistInquiryCommand.kt, src/main/kotlin/kr/kro/dearmoment/inquiry/application/port/input/CreateInquiryUseCase.kt, src/main/kotlin/kr/kro/dearmoment/inquiry/application/port/input/GetInquiryUseCase.kt, src/main/kotlin/kr/kro/dearmoment/inquiry/application/port/output/GetInquiryPort.kt, src/main/kotlin/kr/kro/dearmoment/inquiry/application/port/output/SaveInquiryPort.kt, src/main/kotlin/kr/kro/dearmoment/inquiry/application/query/GetArtistInquiresQuery.kt, src/main/kotlin/kr/kro/dearmoment/inquiry/application/service/InquiryService.kt, src/main/kotlin/kr/kro/dearmoment/inquiry/domain/ArtistInquiry.kt, src/main/kotlin/kr/kro/dearmoment/like/domain/LikeType.kt, src/test/kotlin/kr/kro/dearmoment/common/RestApiTestBase.kt, src/test/kotlin/kr/kro/dearmoment/inquiry/adapter/input/web/artist/ArtistInquiryRestAdapterTest.kt, src/test/kotlin/kr/kro/dearmoment/inquiry/adapter/output/persistence/InquiryPersistenceAdapterTest.kt, src/test/kotlin/kr/kro/dearmoment/inquiry/application/service/InquiryServiceTest.kt, src/test/kotlin/kr/kro/dearmoment/inquiry/domain/ArtistInquiryTest.kt, src/test/kotlin/kr/kro/dearmoment/like/adapter/input/web/LikeRestAdapterTest.kt, src/test/kotlin/kr/kro/dearmoment/like/adapter/output/persistence/LikePersistenceAdapterTest.kt, src/test/kotlin/kr/kro/dearmoment/like/application/service/LikeServiceTest.kt, src/test/kotlin/kr/kro/dearmoment/like/domain/LikeTest.kt
=> rename: 작가 author -> artist로 수정

src/main/kotlin/kr/kro/dearmoment/inquiry/adapter/input/web/ArtistInquiryRestAdapter.kt, src/main/kotlin/kr/kro/dearmoment/inquiry/adapter/input/web/ProductInquiryRestAdapter.kt, src/main/kotlin/kr/kro/dearmoment/inquiry/adapter/input/web/ServiceInquiryRestAdapter.kt, src/main/kotlin/kr/kro/dearmoment/inquiry/application/dto/CreateArtistInquiryRequest.kt, src/main/kotlin/kr/kro/dearmoment/inquiry/application/dto/CreateInquiryResponse.kt, src/main/kotlin/kr/kro/dearmoment/inquiry/application/dto/CreateProductInquiryRequest.kt, src/main/kotlin/kr/kro/dearmoment/inquiry/application/dto/CreateServiceInquiryRequest.kt, src/main/kotlin/kr/kro/dearmoment/inquiry/application/dto/GetArtistInquiryResponse.kt, src/main/kotlin/kr/kro/dearmoment/inquiry/application/dto/GetProductInquiryResponse.kt, src/main/kotlin/kr/kro/dearmoment/inquiry/application/port/input/CreateInquiryUseCase.kt, src/main/kotlin/kr/kro/dearmoment/inquiry/application/port/input/GetInquiryUseCase.kt, src/main/kotlin/kr/kro/dearmoment/inquiry/application/service/InquiryService.kt, src/test/kotlin/kr/kro/dearmoment/common/RestApiTestBase.kt, src/test/kotlin/kr/kro/dearmoment/inquiry/adapter/input/web/artist/ArtistInquiryRestAdapterTest.kt, src/test/kotlin/kr/kro/dearmoment/inquiry/adapter/input/web/product/ProductInquiryRestAdapterTest.kt, src/test/kotlin/kr/kro/dearmoment/inquiry/adapter/input/web/service/ServiceInquiryRestAdapterTest.kt
=> 문의 dto 패키지 리팩토링

.github/workflows/deploy-to-production.yml, .github/workflows/docker-publish.yml
이슈 번호: N/A
secrets - Actions  <-> CD workflow의 스크립트 참조되도록 등록및 체크 필요
=> CD workflow 배포 작업과 동일하게 작성, env 파일 secrets 참조하도록 추가

.github/workflows/docker-publish.yml
=> chore: CI - docker-publish.yml mail, OBJECT_STORAGE env 추가

.github/workflows/docker-publish.yml
=> chore: docker-publish.yml 오타 수정

.github/workflows/deploy-to-production.yml
=> fix: deploy-to-production.yml

.github/workflows/deploy-to-production.yml
=> chore: CD - ghcr pull latest -> SHA 로 변경

.github/workflows/deploy-to-production.yml
=> chore: CD-Workflow 오타수정

.github/workflows/deploy-to-production.yml
=> chore: remove dangling image

src/main/kotlin/kr/kro/dearmoment/product/adapter/out/persistence/ProductEntity.kt, src/main/kotlin/kr/kro/dearmoment/product/adapter/out/persistence/ProductOptionEntity.kt
이슈 번호: N/A
- 테이블의 nullable 하지 않은 컬럼값에 기본값을 넣지 않아 실행시 예외가 발생해서 수정
=> fix: 카운터 컬럼 기본값 추가

src/main/kotlin/kr/kro/dearmoment/like/adapter/output/persistence/LikeReadOnlyPersistenceAdapter.kt, src/main/kotlin/kr/kro/dearmoment/like/application/port/output/GetLikePort.kt, src/main/kotlin/kr/kro/dearmoment/product/adapter/input/web/ProductRestAdapter.kt, src/main/kotlin/kr/kro/dearmoment/product/application/dto/response/GetProductOptionResponse.kt, src/main/kotlin/kr/kro/dearmoment/product/application/dto/response/GetProductResponse.kt, src/main/kotlin/kr/kro/dearmoment/product/application/usecase/get/GetProductUseCaseImpl.kt, src/test/kotlin/kr/kro/dearmoment/product/adapter/input/web/get/GetProductRestAdapterTest.kt, src/test/kotlin/kr/kro/dearmoment/product/application/usecase/get/GetProductUseCaseTest.kt
=> feat: 상품 조회에 좋아요 id 추가

src/main/kotlin/kr/kro/dearmoment/like/adapter/output/persistence/LikeReadOnlyPersistenceAdapter.kt, src/test/kotlin/kr/kro/dearmoment/like/adapter/output/persistence/LikeReadOnlyPersistenceAdapterTest.kt
=> feat: 유저의 상품 좋아요 쿼리 조회 작성

src/main/kotlin/kr/kro/dearmoment/product/application/dto/response/GetProductOptionResponse.kt
=> feat: add originalProvided field to GetProductOptionResponse DTO

src/main/kotlin/kr/kro/dearmoment/common/dto/PagedResponse.kt, src/main/kotlin/kr/kro/dearmoment/inquiry/application/service/InquiryQueryService.kt, src/main/kotlin/kr/kro/dearmoment/like/application/service/LikeQueryService.kt, src/main/kotlin/kr/kro/dearmoment/product/application/usecase/search/ProductSearchUseCaseImpl.kt, src/test/kotlin/kr/kro/dearmoment/inquiry/adapter/input/web/ProductOptionInquiryRestAdapterTest.kt, src/test/kotlin/kr/kro/dearmoment/inquiry/adapter/input/web/StudioInquiryRestAdapterTest.kt, src/test/kotlin/kr/kro/dearmoment/inquiry/application/service/InquiryQueryServiceTest.kt, src/test/kotlin/kr/kro/dearmoment/like/adapter/input/web/ProductLikeRestAdapterTest.kt, src/test/kotlin/kr/kro/dearmoment/like/adapter/input/web/ProductOptionLikeRestAdapterTest.kt, src/test/kotlin/kr/kro/dearmoment/like/application/service/LikeQueryServiceTest.kt, src/test/kotlin/kr/kro/dearmoment/product/adapter/input/web/search/SearchProductRestAdapterTest.kt
=> remove: 미사용 프로퍼티 제거

src/main/kotlin/kr/kro/dearmoment/studio/application/command/ModifyStudioCommand.kt, src/main/kotlin/kr/kro/dearmoment/studio/application/dto/request/ModifyStudioRequest.kt, src/test/kotlin/kr/kro/dearmoment/studio/adapter/input/StudioRestAdapterTest.kt, src/test/kotlin/kr/kro/dearmoment/studio/application/service/StudioServiceTest.kt
=> feat: 스튜디오 수정 요청 바디에 영입 여부 추가

src/main/kotlin/kr/kro/dearmoment/like/adapter/output/persistence/LikeReadOnlyPersistenceAdapter.kt, src/main/kotlin/kr/kro/dearmoment/product/adapter/out/persistence/ProductReadOnlyRepository.kt
=> feat: createQuery.singleResult -> resultList로 수정

src/main/kotlin/kr/kro/dearmoment/like/application/dto/GetProductOptionLikeResponse.kt, src/main/kotlin/kr/kro/dearmoment/product/adapter/out/persistence/ProductEntity.kt, src/main/kotlin/kr/kro/dearmoment/product/adapter/out/persistence/ProductReadOnlyRepository.kt, src/main/kotlin/kr/kro/dearmoment/product/application/port/out/GetProductPort.kt, src/main/kotlin/kr/kro/dearmoment/product/application/usecase/search/ProductSearchUseCaseImpl.kt, src/test/kotlin/kr/kro/dearmoment/like/adapter/input/web/ProductOptionLikeRestAdapterTest.kt, src/test/kotlin/kr/kro/dearmoment/product/adapter/out/persistence/ProductReadOnlyPersistenceRepositoryTest.kt
=> refactor: 상품 조회 중복 코드 제거

src/main/kotlin/kr/kro/dearmoment/like/adapter/input/web/ProductLikeRestAdapter.kt, src/main/kotlin/kr/kro/dearmoment/like/adapter/input/web/ProductOptionLikeRestAdapter.kt, src/main/kotlin/kr/kro/dearmoment/like/adapter/output/persistence/LikeReadOnlyPersistenceAdapter.kt, src/main/kotlin/kr/kro/dearmoment/like/adapter/output/persistence/ProductLikeEntity.kt, src/main/kotlin/kr/kro/dearmoment/like/adapter/output/persistence/ProductLikeJpaRepository.kt, src/main/kotlin/kr/kro/dearmoment/like/adapter/output/persistence/ProductOptionLikeEntity.kt, src/main/kotlin/kr/kro/dearmoment/like/adapter/output/persistence/ProductOptionLikeJpaRepository.kt, src/main/kotlin/kr/kro/dearmoment/like/application/dto/FilterUserLikesRequest.kt, src/main/kotlin/kr/kro/dearmoment/like/application/port/input/LikeQueryUseCase.kt, src/main/kotlin/kr/kro/dearmoment/like/application/port/output/GetLikePort.kt, src/main/kotlin/kr/kro/dearmoment/like/application/query/FilterUserLikesQuery.kt, src/main/kotlin/kr/kro/dearmoment/like/application/service/LikeQueryService.kt, src/test/kotlin/kr/kro/dearmoment/common/fixture/DomainFixtureFactory.kt, src/test/kotlin/kr/kro/dearmoment/like/adapter/input/web/ProductLikeRestAdapterTest.kt, src/test/kotlin/kr/kro/dearmoment/like/adapter/input/web/ProductOptionLikeRestAdapterTest.kt, src/test/kotlin/kr/kro/dearmoment/like/adapter/output/persistence/LikeReadOnlyPersistenceAdapterTest.kt, src/test/kotlin/kr/kro/dearmoment/like/application/service/LikeQueryServiceTest.kt, src/test/kotlin/kr/kro/dearmoment/product/adapter/input/web/search/SearchProductRestAdapterTest.kt
이슈 번호: #114 
- 유저의 좋아요(상품, 옵션)을 필터링
=> feat: 나의 상품, 옵션 찜 필터 구현 #114

src/main/kotlin/kr/kro/dearmoment/user/adapter/input/web/KakaoOAuthController.kt, src/main/kotlin/kr/kro/dearmoment/user/application/service/KakaoOAuthService.kt
=> test: 실패시 에러 코드 전달, 강제 실패 코드 (삭제 예정) 추가

src/main/kotlin/kr/kro/dearmoment/user/adapter/input/web/KakaoOAuthController.kt, src/main/kotlin/kr/kro/dearmoment/user/application/service/KakaoOAuthService.kt
=> fix: 주석수정, 실패 코드 제거, 주소 수정

src/main/kotlin/kr/kro/dearmoment/user/adapter/output/persistence/UserEntity.kt, src/main/kotlin/kr/kro/dearmoment/user/application/dto/request/UpdateUserRequest.kt, src/main/kotlin/kr/kro/dearmoment/user/application/dto/response/UserResponse.kt, src/main/kotlin/kr/kro/dearmoment/user/application/dto/response/UserStudioResponse.kt, src/main/kotlin/kr/kro/dearmoment/user/application/service/UserProfileService.kt, src/main/kotlin/kr/kro/dearmoment/user/domain/User.kt, src/test/kotlin/kr/kro/dearmoment/user/domain/UserTest.kt
이슈 번호: N/A
유저 조회/업데이트 시 
추가 입력 정보 유무 필드 추가
=> feat: user 초기정보 입력 유무 컬럼 추가

src/main/kotlin/kr/kro/dearmoment/image/adapter/output/objectstorage/OracleObjectStorageAdapter.kt, src/main/kotlin/kr/kro/dearmoment/image/adapter/output/objectstorage/OracleObjectStorageUtil.kt
=> 객체 스토리지 클라이언트 초기화 로직 롤백

src/main/kotlin/kr/kro/dearmoment/product/adapter/out/persistence/ProductOptionRepositoryAdapter.kt, src/test/kotlin/kr/kro/dearmoment/product/adapter/out/persistence/ProductOptionPersistenceAdapterTest.kt
=> refactor: remove duplicate option name validation 

src/main/kotlin/kr/kro/dearmoment/product/application/dto/request/UpdateProductRequest.kt, src/main/kotlin/kr/kro/dearmoment/product/application/dto/response/ProductResponse.kt, src/test/kotlin/kr/kro/dearmoment/product/adapter/input/web/create/CreateProductRestAdapterTest.kt, src/test/kotlin/kr/kro/dearmoment/product/adapter/input/web/update/UpdateProductRestAdapterTest.kt
=> feat: add originalProvided field to product response and update related

src/main/resources/application.yml
=> chore: multipart 최대 사이즈 하향 #142
